apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  labels:
  name: letsencrypt-liveclass
spec:
  acme:
    email: devops-team@darey.io
    privateKeySecretRef:
      name: letsencrypt-liveclass-key
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        route53:
          hostedZoneID: Z07965101TA1KUADZ6597
          region: eu-west-2
      selector:
        dnsZones:
        - liveclass.training.darey.io
