name: Build and Push Docker Images

# Trigger events https://docs.github.com/en/actions/using-workflows/triggering-a-workflow
on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

# Actions from the GitHub Marketplace are pre-built, reusable components that you can use in your GitHub Actions workflows. They are created and shared by the community and provide specific functionality to automate different tasks in your software development workflows.
#  https://github.com/marketplace?type=actions.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

# https://github.com/marketplace/actions/docker-login
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      - name: debug
        run: |
          pwd
          ls -latr

      - name: Build and push Backend Docker image
# The working-directory is a parameter in GitHub Actions that allows you to specify the working directory for a particular step in your workflow.
# By default, each step in a workflow runs in the root directory of the repository. However, there are cases where you may want to execute a step in a specific directory within your repository.
        working-directory: Orchestration/cicd/finmoney-app/backend
# Common directives `name`, `on`, `jobs`, `steps`, `env`, `if`, `run`, `uses`
        run: |
          docker build -t finmoney-app-backend .
          docker push dareyregistry/finmoney-app-backend

      - name: Build and push Frontend Docker image
        working-directory: Orchestration/cicd/finmoney-app/frontend
        run: |
          docker build -t finmoney-app-frontend .
          docker push dareyregistry/finmoney-app-frontend

      - name: Build and push Database Docker image
        working-directory: Orchestration/cicd/finmoney-app/database
        run: |
          docker build -t finmoney-app-database .
          docker push dareyregistry/finmoney-app-database
